upsource:
    # build: .
    image: saeedmasoumi/centos7-upsource
    container_name: upsource
    restart: always
    ports:
        - 8080:8080
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/upsource:/var/lib/upsource
        - /data/upsource/conf:/opt/upsource/conf
    ulimits:
        memlock: -1
        nofile: 100000
        nproc: 32768